### ISSUE TITLE
Unable to connect to SSL server

### ISSUE THREAD

**Issue by Elizafox** [xchataqua/xchataqua#214] opened 2016-07-01 21:43 UTC
Hey,

I can't connect to my bouncer, which uses SSL on a nonstandard port. I get the following error:

```
 * Connection failed. Error: (336085247) error:140840FF:SSL routines:SSL3_CONNECT:unknown state
```

I'm willing to help debug the issue further.

**Comment by manjiki** [comment] 2016-07-02 07:55
I can't connect to any port using SSL, I get the same issue in OSX version is 10.10.5

**Comment by CoreISP** [comment] 2016-07-02 22:09
Same problem here, installed latest update from App Store that said "SSL fixes"; ever since: SSL no longer works at all.

**Comment by whatzaum** [comment] 2016-07-02 23:47
> Same problem here, installed latest update from App Store that said "SSL fixes"; ever since: SSL no longer works at all.

^ Same issue. My config has not changed and could use SSL connection previously to update 1.17.3 on
OS X 10.11.5

**Comment by mitral** [comment] 2016-07-03 01:19
Same here, I can't connect at all, I first thought it was just me but looks like I'm not alone. Seems this client is getting worse

**Comment by manjiki** [comment] 2016-07-03 07:14
Where I can find a build of the previous version?

**Comment by unsound** [comment] 2016-07-03 08:35
+1, I'm getting <code>error:140840FF:SSL routines:SSL3_CONNECT:unknown state</code> with latest OS X 10.11.5. (Has this release been tested at all?)

**Comment by unsound** [comment] 2016-07-03 08:42
Manually downgrading to version 1.17.2 from the package at https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.2 fixes the problem for me.

**Comment by youknowone** [comment] 2016-07-03 11:29
I am really sorry for this problem. I am uploading new version and it will be accepted in a few days. (app store review is faster recently)

**Comment by youknowone** [comment] 2016-07-03 11:44
Can you try 1.17.4 pre-release? https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.4

**Comment by manjiki** [comment] 2016-07-03 14:55
It is crashing, but it says
`Exception Type:        EXC_CRASH (Code Signature Invalid)`

**Comment by adam234** [comment] 2016-07-03 17:12
Downloaded the pkg version from https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.4, it crashes on Macos 10.11.5

% /Applications/XChat\ Azure.app/Contents/MacOS/XChat\ Azure
Killed
% uname -a 
Darwin dali.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

**Comment by youknowone** [comment] 2016-07-04 04:37
1.17.4 is updated in App Store. It is fixing known SSL issues.

**Comment by adam234** [comment] 2016-07-04 04:50
App store 1.7.4 seems to work, unlike the release I got from the pkg at https://github.com/xchataqua/xchataqua/releases/tag/appstore-1.17.4

**Comment by manjiki** [comment] 2016-07-04 05:36
SSL connections work for me as well (>2 connections)

**Comment by dschallert** [comment] 2016-07-04 07:27
same here, 1.17.4 fixed it   👍

**Comment by unsound** [comment] 2016-07-04 07:34
I can also confirm that the problem is fixed in the latest App Store version (appstore-1.17.4-0-g1b1c703/2.8.8-svn1523). Thanks @youknowone!

**Comment by youknowone** [comment] 2016-07-04 07:55
Thanks for confirming, and I am really sorry for the problem

**Closed by youknowone** 2016-07-04 07:55 UTC
